# 1
services:
  backend:
    container_name: digital_bazaar-backend
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py csu &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

    environment:
      - POSTGRES_HOST=db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


  db:
    container_name: digital_bazaar-db
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 10

  nginx:
    build: ./nginx
    ports:
      - "8082:8082"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles

    depends_on:
      - backend


networks:
  default:

volumes:

  postgres_data:
  static_volume:
