# Generated by Django 4.2.2 on 2025-04-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network_nodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="укажите название продукта",
                        max_length=255,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="укажите модель продукта",
                        max_length=255,
                        verbose_name="Модель продукта",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        help_text="укажите дату выхода на рынок",
                        verbose_name="Дата выхода на рынок",
                    ),
                ),
                (
                    "network_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="network_nodes.networknode",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("network_node", "name", "model"), name="unique_product_per_node"
            ),
        ),
    ]
